# Generated by Django 3.0.2 on 2021-01-07 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='time_insert',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 7, 11, 48, 33, 613743, tzinfo=utc), editable=False),
        ),
    ]
